version: '3.3'

services:
  postgres-dev:
    image: postgres:13
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=lottery
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5431:5432'
    volumes:
      - ./postgres_data_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass contrasena
    ports:
      - "6379:6379"
    volumes: 
      - ./redis_data:/data
  
  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight_data:/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
