version: '3.3'

services:
  postgres-dev:
    image: postgres:13
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=lottery
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5431:5432'
    volumes:
      - ./postgres_data_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"