name: Proceso de CI/CD Basico

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install depends
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
