name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build docker image backend-advanced
        run: docker build -f Dockerfile.main -t backend-advanced .
      - name: Build docker image notifications microservice
        run: docker build -f Dockerfile.notifications -t notifications .
      - name: Push docker images
        run: |
          docker tag backend-advanced ${{ secrets.DOCKER_USERNAME }}/backend-advanced
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-advanced
          docker tag notifications ${{ secrets.DOCKER_USERNAME }}/notifications
          docker push ${{ secrets.DOCKER_USERNAME }}/notifications
